[connections.snowflake]
account = "FQIUTPH-YQB79132"
user = "harpritsingh"
password = "071256214481!sS"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = "true"